### ISSUE TITLE
Integrate Phinx or other migration database system

### ISSUE THREAD

**Issue by GoldraK** [maurobonfietti/slim4-api-skeleton#21]
Hi,

I think is a good idea integrate phinx or other migration database system to management the database and change the unit test to sqlite memory for user CI/CD more easy.

I already have phinx set, if I can integrate the unit tests well I perform a pull request, but it is costing me more than I thought.

Good Skeleton

**Comment by maurobonfietti** [comment]
Hi @GoldraK ,

I think could be a good idea too, but maybe, in my other repo.

This one:

https://github.com/maurobonfietti/rest-api-slim-php

Because at this moment, I prefer to keep this skeleton **as simple as possible**.

I think might be better, integrate phinx (or other migration database system) in this repo: [rest-api-slim-php](https://github.com/maurobonfietti/rest-api-slim-php).

Thank you very much!

**Comment by GoldraK** [comment]
Hi @maurobonfietti 

I don't see the other project before, I go to check.

Thanks
