### ISSUE TITLE
Role based authorization

### ISSUE THREAD

**Issue by devlamine** [maurobonfietti/slim4-api-skeleton#57]
Hello, I hope all is well with you.

What is the best way to implement a role based authentication and authorization system in slim4-api-skeleton

My app will have three different users - (admin, Author,Editor ...). 
I want to configure allowed groups to a route ?

Thanks

**Comment by DLzer** [comment]
How you _authenticate_ users to the API is one thing. That depends on you're design completely. As for authorizing access to routes based on specific roles I believe the preferred pattern is to create your own middleware for RoleBasedAuth. Then in the `Routes.php` you can specify which routes to add your middleware to: `$app->get('/adminsOnly', ...)->add(AdminOnlyAuth::class);`

**Comment by DLzer** [comment]
In my opinion I would **not** append attributes at the middleware level. You want to keep each component as simple as possible while following the single responsibility principle. In that case I would have by database set up like:

`x_students`
`x_teachers`
`x_students_to_teachers`

With the `x_students_to_teachers` being a join based on a constraint column like `x_students.teacher_id = x.teachers.id`. Then I would have the routes set up like so:

`/students/{id}` -> StudentReaderAction -> StudentReaderService <- Returns a single student
`/students/teacher/{id}` -> StudentFinderAction -> StudentFinderService <- Returns a list of students based on teacher ID
`/students` -> StudentFinderAction -> StudentFinderService <- Returns a list of all students

Where the StudentFinderService is more-so parsing a constant ( the route ) instead of accepting something that is variable a role attribute.

Then your middleware could look like:

```
$app->group('/students', function( RouteCollectorProxy( $app ) {
    
    // Only director ( or above ) can access
    $app->get('', App\Action\StudentFinderAction::class)->add(DirectorMiddleware);
    // Only specific teacher ( or above ) can access
    $app->get('/teacher/{id}', App\Action\StudentFinderAction::class)->add(TeacherMiddleware);

});
```

Hope that clarified a bit more.

**Comment by DLzer** [comment]
I'm sorry I can't comment to much on client-side development. However, I can say while working with my front end devs that typically you would want to use the JWT returned from authenticating the user to determine role, and create 'Role dependent components' based off of that. An Admin should have a different dashboard then a Directory, and same with a Director verses a Teacher.
